language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
#Commands to run test
script:
  - python -m unittest discover -s Tests
branches:
  only:
    - master
    - development
